### ISSUE TITLE
Boot Failed, Connection Reset by Peer

### ISSUE THREAD

**Issue by PaulWoitaschek** [bitrise-steplib/steps-wait-for-android-emulator#10]
My builds are flaky because the emulator sometimes doesn't boot:

```
+------------------------------------------------------------------------------+

| (8) wait-for-android-emulator                                                |
+------------------------------------------------------------------------------+
| id: wait-for-android-emulator                                                |
| version: 1.0.4                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2018-03-19T10:26:52Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[10:26:52] Start installing (golang) with apt-get       
INFO[10:26:52]  * [OK] Step dependency (go) installed, available. 
Configs:
- emulatorSerial: emulator-5554
- bootTimeout: 300
- AndroidHome: /opt/android-sdk-linux
Waiting for emulator boot
> Checking if device booted...
Running command timed out, retry...
> Checking if device booted...
Failed to check emulator boot status, error: error: protocol fault (couldn't read status): Connection reset by peer - exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | wait-for-android-emulator (exit code: 1)                      | 29 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...com/bitrise-steplib/steps-wait-for-android-emulator/issues |
| Source: https://github.com/bitrise-steplib/steps-wait-for-android-emulator   |
+---+---------------------------------------------------------------+----------+
```

**Comment by viktorbenei** [comment]
Can you please link the build's URL @PaulWoitaschek ?

**Comment by PaulWoitaschek** [comment]
Sure:  https://www.bitrise.io/build/9896c30d82f8117a

**Comment by viktorbenei** [comment]
Thanks, we'll check it ASAP! :)

**Comment by trapacska** [comment]
Hey @PaulWoitaschek !

Checked the step, and seems like you've got your emulator hanging. This issue is related to google's emulator, and the step cannot reach emulator status, please re-run the build and next time it must work just fine.

At the same time, I suggest you to move on with Virtual Device Testing instead. It is more reliable, and in some cases it might be faster as well.

Closing this issue now because it is not an issue with the step itself, please feel free to re-open if you still encounter any issue with the step.

🚀

**Comment by PaulWoitaschek** [comment]
Hm, I was suggested to use this step because virtual device testing does not support multiple apks. :/

**Comment by trapacska** [comment]
@viktorbenei: `protocol fault` is that the bridge between qemu and the android os is disconnected. Can be because one of the two is crashed. If qemu then KVM issue, if android then os issue.

@PaulWoitaschek please find me on our public Bitrise slack channel, we'll sort it out somehow! 🙂

**Comment by viktorbenei** [comment]
One more note @PaulWoitaschek - if you want to use Firebase Test Lab with multiple APKs that's also possible, just not with our built in feature. Can be done by using your own Google FBTL account, related howto: https://discuss.bitrise.io/t/how-to-run-android-tests-on-firebase-testlab/2192
