### ISSUE TITLE
UnlockDevice command failed, error: exit status 1

### ISSUE THREAD

**Issue by hinewwiner** [bitrise-steplib/steps-wait-for-android-emulator#15]
On my Bitrise workflow, I use AVD Manager (1.0.1) to start emulator with the following configs

1. Device Profile : Pixel
2. Android API Level : 29
3. OS Tag : google_apis_playstore
4. ABI : x86
5. ID : emulator
6. Create AMD command flags : --sdcard 512M
7. Start AMD command flags : -no-snapshot -no-audio -no-window -gpu off

However, Wait for android emulator fails with following error : 

+------------------------------------------------------------------------------+

| (10) wait-for-android-emulator@1                                             |
+------------------------------------------------------------------------------+
| id: wait-for-android-emulator                                                |
| version: 1.0.4                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-10-25T23:14:42Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[23:14:42] Start installing (golang) with apt-get       
INFO[23:14:42]  * [OK] Step dependency (go) installed, available. 
Configs:
- emulatorSerial: emulator-5554
- bootTimeout: 30000
- AndroidHome: /opt/android-sdk-linux
Waiting for emulator boot
> Checking if device booted...
> Checking if device booted...
> Checking if device booted...
> Checking if device booted...
> Checking if device booted...
> Checking if device booted...
> Checking if device booted...
> Checking if device booted...
> Checking if device booted...
> Checking if device booted...
> Checking if device booted...
> Checking if device booted...
UnlockDevice command failed, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | wait-for-android-emulator@1 (exit code: 1)                    | 1.3 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...com/bitrise-steplib/steps-wait-for-android-emulator/issues |
| Source: https://github.com/bitrise-steplib/steps-wait-for-android-emulator   |
+---+---------------------------------------------------------------+----------+

Do I need to change something to make it work?

Thank you

**Comment by mjones-droid** [comment]
Make sure you also have the following command flags:
`-camera-back none -camera-front none`

Turning on the simulated camera tends to push beyond the limits of our VM's at the moment. We are working to get this resolved and should have more to announce in the near future. 

Matthew
Senior Customer Engineer
